apiVersion: apps/v1
kind: Deployment
metadata:
  name: prestasifrontend
spec:
  replicas: 5
  selector:
    matchLabels:
      app: prestasifrontend
  template:
    metadata:
      labels:
        app: prestasifrontend
    spec:
      containers:
        - name: frontend
          image: prestasifrontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: prestasifrontend-service
spec:
  type: NodePort
  selector:
    app: prestasifrontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
